services:
  db:
    image: postgres:16
    container_name: dorm-made-db
    environment:
      POSTGRES_DB: dorm-made
      POSTGRES_USER: dorm-made
      POSTGRES_PASSWORD: D0rm-M4d3_2025
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
